# Generated by Django 5.2.4 on 2025-12-18 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='原料名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='原料说明')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价(元/kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '原料',
                'verbose_name_plural': '原料',
            },
        ),
        migrations.CreateModel(
            name='IngredientNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dm', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='干物质(DM)')),
                ('calcium', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='钙(Ca)')),
                ('protein', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='粗蛋白(CP)')),
                ('phosphorus', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='磷(P)')),
                ('ndf', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='中性洗涤纤维(NDF)')),
                ('metabolizable_energy', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='代谢能(ME)')),
                ('mp', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='代谢蛋白(MP)')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to='ingredients.ingredient', verbose_name='所属原料')),
            ],
            options={
                'verbose_name': '原料营养含量',
                'verbose_name_plural': '原料营养含量',
            },
        ),
    ]
