# Generated by Django 5.2.4 on 2025-12-26 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomIngredientNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient_name', models.CharField(max_length=50, verbose_name='营养元素名称')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='营养元素值')),
                ('unit', models.CharField(default='%', max_length=20, verbose_name='单位')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_nutrients', to='ingredients.ingredient', verbose_name='所属原料')),
            ],
            options={
                'verbose_name': '自定义原料营养成分',
                'verbose_name_plural': '自定义原料营养成分',
            },
        ),
    ]
