# Generated by Django 5.2.4 on 2025-12-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_ingredient_approved_at_ingredient_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='审核意见'),
        ),
    ]
