# Generated by Django 5.2.4 on 2025-12-30 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_ingredient_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientPendingChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='原料名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='原料说明')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价(元/kg)')),
                ('dm', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='干物质(DM)')),
                ('calcium', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='钙(Ca)')),
                ('protein', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='粗蛋白(CP)')),
                ('phosphorus', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='磷(P)')),
                ('ndf', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='中性洗涤纤维(NDF)')),
                ('metabolizable_energy', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='代谢能(ME)')),
                ('mp', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='代谢蛋白(MP)')),
                ('custom_nutrients', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_change', to='ingredients.ingredient')),
            ],
            options={
                'verbose_name': '原料待审核变更',
                'verbose_name_plural': '原料待审核变更',
            },
        ),
    ]
