# Generated by Django 5.2.4 on 2025-12-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_ingredientpendingchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='draft', max_length=10, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='ingredientnutrient',
            name='calcium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='钙(Ca)'),
        ),
        migrations.AlterField(
            model_name='ingredientnutrient',
            name='metabolizable_energy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='代谢能(ME)'),
        ),
        migrations.AlterField(
            model_name='ingredientnutrient',
            name='phosphorus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='磷(P)'),
        ),
        migrations.AlterField(
            model_name='ingredientnutrient',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='粗蛋白(CP)'),
        ),
        migrations.AlterField(
            model_name='ingredientpendingchange',
            name='calcium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='钙(Ca)'),
        ),
        migrations.AlterField(
            model_name='ingredientpendingchange',
            name='metabolizable_energy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='代谢能(ME)'),
        ),
        migrations.AlterField(
            model_name='ingredientpendingchange',
            name='phosphorus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='磷(P)'),
        ),
        migrations.AlterField(
            model_name='ingredientpendingchange',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='粗蛋白(CP)'),
        ),
    ]
