# Generated by Django 5.2.4 on 2026-01-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_alter_ingredient_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customingredientnutrient',
            name='nutrient_name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='营养元素名称'),
        ),
        migrations.AddField(
            model_name='customingredientnutrient',
            name='nutrient_name_zh_hans',
            field=models.CharField(max_length=50, null=True, verbose_name='营养元素名称'),
        ),
        migrations.AddField(
            model_name='customingredientnutrient',
            name='unit_en',
            field=models.CharField(default='%', max_length=20, null=True, verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='customingredientnutrient',
            name='unit_zh_hans',
            field=models.CharField(default='%', max_length=20, null=True, verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='原料说明'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='description_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='原料说明'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='原料名称'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name_zh_hans',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='原料名称'),
        ),
        migrations.AlterField(
            model_name='ingredientpendingchange',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价(元/吨)'),
        ),
    ]
