# Generated by Django 5.2.4 on 2026-01-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('zh-hans', '中文'), ('en', 'English')], default='zh-hans', max_length=10),
        ),
    ]
