# Generated by Django 5.2.4 on 2025-12-07 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(max_length=50, verbose_name='动物类型')),
                ('body_weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='体重(kg)')),
                ('daily_gain', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='日增重(g)')),
                ('required_protein', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='需求蛋白(%)')),
                ('required_energy', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='需求代谢能(kcal/kg)')),
                ('required_calcium', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='需求钙(%)')),
                ('required_phosphorus', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='需求磷(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '动物营养需求',
                'verbose_name_plural': '动物营养需求',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='原料名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='原料说明')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价(元/kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '原料',
                'verbose_name_plural': '原料',
            },
        ),
        migrations.CreateModel(
            name='IngredientNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='粗蛋白(%)')),
                ('fat', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='粗脂肪(%)')),
                ('fiber', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='粗纤维(%)')),
                ('calcium', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='钙(%)')),
                ('phosphorus', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='磷(%)')),
                ('metabolizable_energy', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='代谢能(kcal/kg)')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to='formulation.ingredient', verbose_name='所属原料')),
            ],
            options={
                'verbose_name': '原料营养含量',
                'verbose_name_plural': '原料营养含量',
            },
        ),
    ]
