# Generated by Django 5.2.4 on 2025-12-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientnutrient',
            name='dm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='干物质(DM)'),
        ),
        migrations.AddField(
            model_name='ingredientnutrient',
            name='mp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='代谢蛋白(MP)'),
        ),
        migrations.AddField(
            model_name='ingredientnutrient',
            name='ndf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='中性洗涤纤维(NDF)'),
        ),
        migrations.AlterField(
            model_name='ingredientnutrient',
            name='calcium',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='钙(Ca)'),
        ),
        migrations.AlterField(
            model_name='ingredientnutrient',
            name='fat',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='粗脂肪(EE)'),
        ),
        migrations.AlterField(
            model_name='ingredientnutrient',
            name='fiber',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='粗纤维(CF)'),
        ),
        migrations.AlterField(
            model_name='ingredientnutrient',
            name='metabolizable_energy',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='代谢能(ME)'),
        ),
        migrations.AlterField(
            model_name='ingredientnutrient',
            name='phosphorus',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='磷(P)'),
        ),
        migrations.AlterField(
            model_name='ingredientnutrient',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='粗蛋白(CP)'),
        ),
    ]
