# Generated by Django 5.2.4 on 2025-12-08 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulation', '0002_ingredientnutrient_dm_ingredientnutrient_mp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedFormulaResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_index', models.IntegerField(verbose_name='帕累托序号')),
                ('total_cost', models.FloatField(verbose_name='成本')),
                ('dm', models.FloatField(verbose_name='DM')),
                ('ndf', models.FloatField(verbose_name='NDF')),
                ('mp', models.FloatField(verbose_name='MP')),
                ('objective_5', models.FloatField(blank=True, null=True)),
                ('objective_6', models.FloatField(blank=True, null=True)),
                ('objective_7', models.FloatField(blank=True, null=True)),
                ('objective_8', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulation.animalrequirement', verbose_name='动物需求方案')),
            ],
        ),
        migrations.CreateModel(
            name='FeedFormulaIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.FloatField(verbose_name='比例')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulation.ingredient')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='formulation.feedformularesult')),
            ],
        ),
    ]
