# Generated by Django 5.2.4 on 2025-12-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulation', '0003_feedformularesult_feedformulaingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='price',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='ingredientnutrient',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='ingredientnutrient',
            name='fiber',
        ),
        migrations.AddField(
            model_name='animalrequirement',
            name='required_dm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='需求干物质(%)'),
        ),
        migrations.AddField(
            model_name='animalrequirement',
            name='required_mp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='需求代谢蛋白(%)'),
        ),
        migrations.AddField(
            model_name='animalrequirement',
            name='required_ndf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='需求中性洗涤纤维(%)'),
        ),
    ]
