# Generated by Django 5.2.4 on 2025-12-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulation', '0004_rename_price_ingredient_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedformularesult',
            name='objective_5',
        ),
        migrations.RemoveField(
            model_name='feedformularesult',
            name='objective_6',
        ),
        migrations.RemoveField(
            model_name='feedformularesult',
            name='objective_7',
        ),
        migrations.RemoveField(
            model_name='feedformularesult',
            name='objective_8',
        ),
        migrations.AddField(
            model_name='feedformularesult',
            name='ca',
            field=models.FloatField(default=0, verbose_name='钙(Ca)'),
        ),
        migrations.AddField(
            model_name='feedformularesult',
            name='cp',
            field=models.FloatField(default=0, verbose_name='粗蛋白(CP)'),
        ),
        migrations.AddField(
            model_name='feedformularesult',
            name='me',
            field=models.FloatField(default=0, verbose_name='代谢能(ME)'),
        ),
        migrations.AddField(
            model_name='feedformularesult',
            name='p',
            field=models.FloatField(default=0, verbose_name='磷(P)'),
        ),
        migrations.AlterField(
            model_name='feedformularesult',
            name='dm',
            field=models.FloatField(default=0, verbose_name='干物质(DM)'),
        ),
        migrations.AlterField(
            model_name='feedformularesult',
            name='mp',
            field=models.FloatField(default=0, verbose_name='代谢蛋白(MP)'),
        ),
        migrations.AlterField(
            model_name='feedformularesult',
            name='ndf',
            field=models.FloatField(default=0, verbose_name='中性洗涤纤维(NDF)'),
        ),
        migrations.AlterField(
            model_name='feedformularesult',
            name='total_cost',
            field=models.FloatField(default=0, verbose_name='成本'),
        ),
    ]
