# Generated by Django 5.2.4 on 2025-12-18 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_requirements', '0001_initial'),
        ('formulation', '0005_remove_feedformularesult_objective_5_and_more'),
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedformularesult',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal_requirements.animalrequirement', verbose_name='动物需求方案'),
        ),
        migrations.RemoveField(
            model_name='ingredientnutrient',
            name='ingredient',
        ),
        migrations.AlterField(
            model_name='feedformulaingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient'),
        ),
        migrations.DeleteModel(
            name='AnimalRequirement',
        ),
        migrations.DeleteModel(
            name='IngredientNutrient',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
