# Generated by Django 5.2.4 on 2025-12-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulation', '0006_alter_feedformularesult_requirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedformulaingredient',
            name='json_feed_formula',
            field=models.TextField(default='', verbose_name='创造yaml文件所需的json数据'),
        ),
    ]
