# Generated by Django 5.2.4 on 2026-01-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulation', '0007_feedformulaingredient_json_feed_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedformularesult',
            name='custom_nutrients',
            field=models.JSONField(default=dict, verbose_name='自定义营养元素'),
        ),
    ]
