# Generated by Django 5.2.4 on 2025-12-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(max_length=50, verbose_name='动物类型')),
                ('body_weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='体重(kg)')),
                ('daily_gain', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='日增重(g)')),
                ('required_dm', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='需求干物质(%)')),
                ('required_calcium', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='需求钙(%)')),
                ('required_protein', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='需求蛋白(%)')),
                ('required_phosphorus', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='需求磷(%)')),
                ('required_ndf', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='需求中性洗涤纤维(%)')),
                ('required_energy', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='需求代谢能(kcal/kg)')),
                ('required_mp', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='需求代谢蛋白(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '动物营养需求',
                'verbose_name_plural': '动物营养需求',
            },
        ),
    ]
