# Generated by Django 5.2.4 on 2025-12-25 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_requirements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animalrequirement',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='animalrequirement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requirements', to=settings.AUTH_USER_MODEL, verbose_name='审核用户'),
        ),
        migrations.AddField(
            model_name='animalrequirement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_requirements', to=settings.AUTH_USER_MODEL, verbose_name='提交用户'),
        ),
        migrations.AddField(
            model_name='animalrequirement',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='审核状态'),
        ),
        migrations.CreateModel(
            name='CustomNutrientRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient_name', models.CharField(max_length=50, verbose_name='营养元素名称')),
                ('nutrient_value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='营养元素值')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_nutrients', to='animal_requirements.animalrequirement', verbose_name='关联的动物营养需求')),
            ],
            options={
                'verbose_name': '自定义营养需求',
                'verbose_name_plural': '自定义营养需求',
            },
        ),
    ]
