# Generated by Django 5.2.4 on 2025-12-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_requirements', '0002_animalrequirement_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalrequirement',
            name='required_calcium',
        ),
        migrations.RemoveField(
            model_name='animalrequirement',
            name='required_dm',
        ),
        migrations.RemoveField(
            model_name='animalrequirement',
            name='required_energy',
        ),
        migrations.RemoveField(
            model_name='animalrequirement',
            name='required_mp',
        ),
        migrations.RemoveField(
            model_name='animalrequirement',
            name='required_ndf',
        ),
        migrations.RemoveField(
            model_name='animalrequirement',
            name='required_phosphorus',
        ),
        migrations.RemoveField(
            model_name='animalrequirement',
            name='required_protein',
        ),
        migrations.RemoveField(
            model_name='customnutrientrequirement',
            name='nutrient_value',
        ),
        migrations.AddField(
            model_name='animalrequirement',
            name='calcium_lower',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='钙下界(%))'),
        ),
        migrations.AddField(
            model_name='animalrequirement',
            name='calcium_upper',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='钙上界(%))'),
        ),
        migrations.AddField(
            model_name='animalrequirement',
            name='dm_lower',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='干物质下界(%))'),
        ),
        migrations.AddField(
            model_name='animalrequirement',
            name='dm_upper',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='干物质上界(%))'),
        ),
        migrations.AddField(
            model_name='animalrequirement',
            name='energy_lower',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='代谢能下界(kcal/kg))'),
        ),
        migrations.AddField(
            model_name='animalrequirement',
            name='energy_upper',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='代谢能上界(kcal/kg))'),
        ),
        migrations.AddField(
            model_name='animalrequirement',
            name='mp_lower',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='代谢蛋白下界(%))'),
        ),
        migrations.AddField(
            model_name='animalrequirement',
            name='mp_upper',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='代谢蛋白上界(%))'),
        ),
        migrations.AddField(
            model_name='animalrequirement',
            name='ndf_lower',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='中性洗涤纤维下界(%))'),
        ),
        migrations.AddField(
            model_name='animalrequirement',
            name='ndf_upper',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='中性洗涤纤维上界(%))'),
        ),
        migrations.AddField(
            model_name='animalrequirement',
            name='phosphorus_lower',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='磷下界(%))'),
        ),
        migrations.AddField(
            model_name='animalrequirement',
            name='phosphorus_upper',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='磷上界(%))'),
        ),
        migrations.AddField(
            model_name='animalrequirement',
            name='protein_lower',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='蛋白下界(%))'),
        ),
        migrations.AddField(
            model_name='animalrequirement',
            name='protein_upper',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='蛋白上界(%))'),
        ),
        migrations.AddField(
            model_name='customnutrientrequirement',
            name='nutrient_lower',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='营养元素下界'),
        ),
        migrations.AddField(
            model_name='customnutrientrequirement',
            name='nutrient_upper',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='营养元素上界'),
        ),
    ]
