# Generated by Django 5.2.4 on 2025-12-30 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_requirements', '0003_remove_animalrequirement_required_calcium_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalrequirement',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='draft', max_length=10, verbose_name='审核状态'),
        ),
        migrations.CreateModel(
            name='AnimalRequirementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='animal_requirements.animalrequirement')),
            ],
            options={
                'verbose_name': '动物营养需求历史版本',
                'verbose_name_plural': '动物营养需求历史版本',
                'ordering': ['-created_at'],
            },
        ),
    ]
