# Generated by Django 5.2.4 on 2025-12-30 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_requirements', '0004_alter_animalrequirement_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalRequirementPendingChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(max_length=50, verbose_name='动物类型')),
                ('body_weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='体重(kg)')),
                ('daily_gain', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='日增重(g)')),
                ('dm_lower', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='干物质下界(%))')),
                ('dm_upper', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='干物质上界(%))')),
                ('calcium_lower', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='钙下界(%))')),
                ('calcium_upper', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='钙上界(%))')),
                ('protein_lower', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='蛋白下界(%))')),
                ('protein_upper', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='蛋白上界(%))')),
                ('phosphorus_lower', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='磷下界(%))')),
                ('phosphorus_upper', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='磷上界(%))')),
                ('ndf_lower', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='中性洗涤纤维下界(%))')),
                ('ndf_upper', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='中性洗涤纤维上界(%))')),
                ('energy_lower', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='代谢能下界(kcal/kg))')),
                ('energy_upper', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='代谢能上界(kcal/kg))')),
                ('mp_lower', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='代谢蛋白下界(%))')),
                ('mp_upper', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='代谢蛋白上界(%))')),
                ('custom_nutrients', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requirement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_change', to='animal_requirements.animalrequirement')),
            ],
            options={
                'verbose_name': '动物营养需求待审核变更',
                'verbose_name_plural': '动物营养需求待审核变更',
            },
        ),
    ]
