# Generated by Django 5.2.4 on 2026-01-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_requirements', '0005_animalrequirementpendingchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalrequirement',
            name='animal_type_en',
            field=models.CharField(max_length=50, null=True, verbose_name='动物类型'),
        ),
        migrations.AddField(
            model_name='animalrequirement',
            name='animal_type_zh_hans',
            field=models.CharField(max_length=50, null=True, verbose_name='动物类型'),
        ),
        migrations.AddField(
            model_name='customnutrientrequirement',
            name='nutrient_name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='营养元素名称'),
        ),
        migrations.AddField(
            model_name='customnutrientrequirement',
            name='nutrient_name_zh_hans',
            field=models.CharField(max_length=50, null=True, verbose_name='营养元素名称'),
        ),
        migrations.AddField(
            model_name='customnutrientrequirement',
            name='unit_en',
            field=models.CharField(max_length=20, null=True, verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='customnutrientrequirement',
            name='unit_zh_hans',
            field=models.CharField(max_length=20, null=True, verbose_name='单位'),
        ),
    ]
